name: tojam2020
description: Playing around with DART in preparation for TOJam 2020

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  js: ^0.6.0
  
dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
